In [1]:
# brackets are always used to access a list, tuple, set, dict
x = {"A":4, "B":3}
x["A"]

4

In [2]:
# this is kind of a pain, there are easier and quicker ways
states = ("AL","AK")
pop = {"AL":6_000_000,"AK":1_000_000}

In [1]:
python_list = list(range(293_071))

In [2]:
%%time
total = 0
for x in python_list:
    total += x

CPU times: total: 46.9 ms
Wall time: 48.9 ms


In [5]:
python_list = list(range(29_307_100))

In [6]:
%%time
total = 0
for x in python_list:
    total += x

CPU times: total: 4 s
Wall time: 4.04 s


In [4]:
# Works for vector and raster data
# Not nearly as flexible as what is built in (can't mix int and str)
# numpy is often in the backend of things
import numpy as np

In [5]:
# numpy will use Python lists and spits it out as a numpy array.
x = [1,2,3]
test_arr = np.array(x)

In [6]:
test_arr

array([1, 2, 3])

In [7]:
# Python can't do this! Scalar operation like a vector. (1 + 3 = 4, 2 + 3 = 5, etc.)
test_arr + 3

array([4, 5, 6])

In [18]:
test_arr ** 2

array([1, 4, 9])

In [8]:
# You can add numpy arrays of the same shape. If you try to add [x,y,z] and [x,y] you'll get an error.
test_arr + [3,4,5]

array([4, 6, 8])

In [11]:
# arange works like (start,stop,step)
test_arr = np.arange(0,100, 2)
test_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [31]:
# creates a 20x20 matrix that is just full of zeros for some reason
test_arr = np.zeros((20,20))
test_arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [12]:
# shape of array
test_arr.shape

(50,)

In [13]:
# total points of the array
test_arr.size

50

In [14]:
# linspace = return evenly space samples, bounded by square brackets on both sides. Good for color plots!
# this example, provides 5 evenly spaced values between 30 and 40
test_arr_1 = np.arange(0,10)
test_arr_2 = np.linspace(30,40,5)
test_arr_2

array([30. , 32.5, 35. , 37.5, 40. ])

In [15]:
# concatenate smacks the two arrays side by side and boom they're one array. This case, they're not assigned to a new array
np.concat([test_arr_1, test_arr_2])

array([ 0. ,  1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 30. ,
       32.5, 35. , 37.5, 40. ])

In [16]:
# axis=0 just puts them together: regular concat
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
# axis=1 looks at the same position of each array and creates a new array from those.
# for this example, [1,2] and [5,6] are both position 0, so it'll combine position 0 values
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
np.concatenate((x,y),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
# Pandas is a library for dealing with TABULAR data (i love excel i love excel i love excel)
# Works fast on big tabular data sets! However, almost unusable for raster data.
# Easily performs groupby operations (e.g. states)
import pandas as pd

In [1]:
import pandas as pd
import numpy as np

In [13]:
squirrel_dataset = pd.read_csv("C:/Users/thewe/Downloads/2018_Central_Park_Squirrel_Census_-_Squirrel_Data_20260205.csv", 
                               parse_dates=["Date"], date_format="%m%d%Y")

In [14]:
squirrel_dataset

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,2018-10-14,3,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086)
1,-73.968857,40.783783,21B-AM-1019-04,21B,AM,2018-10-19,4,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9688574691102 40.7837825208444)
2,-73.974281,40.775534,11B-PM-1014-08,11B,PM,2018-10-14,8,NaN,Gray,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.97428114848522 40.775533619083)
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,2018-10-17,14,Adult,Gray,NaN,...,False,False,False,False,False,False,False,True,NaN,POINT (-73.9596413903948 40.7903128889029)
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,2018-10-17,5,Adult,Gray,Cinnamon,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9702676472613 40.7762126854894)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3018,-73.963943,40.790868,30B-AM-1007-04,30B,AM,2018-10-07,4,Adult,Gray,NaN,...,False,False,False,False,False,False,False,True,NaN,POINT (-73.9639431360458 40.7908677445466)
3019,-73.970402,40.782560,19A-PM-1013-05,19A,PM,2018-10-13,5,Adult,Gray,White,...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9704015859639 40.7825600069973)
3020,-73.966587,40.783678,22D-PM-1012-07,22D,PM,2018-10-12,7,Adult,Gray,"Black, Cinnamon, White",...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9665871993517 40.7836775064883)
3021,-73.963994,40.789915,29B-PM-1010-02,29B,PM,2018-10-10,2,NaN,Gray,"Cinnamon, White",...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9639941227864 40.7899152327912)


In [15]:
# looking for the column
squirrel_dataset['Date']

0      2018-10-14
1      2018-10-19
2      2018-10-14
3      2018-10-17
4      2018-10-17
          ...    
3018   2018-10-07
3019   2018-10-13
3020   2018-10-12
3021   2018-10-10
3022   2018-10-12
Name: Date, Length: 3023, dtype: datetime64[us]

In [16]:
squirrel_dataset.groupby("Date").count()['X']

Date
2018-10-06    337
2018-10-07    405
2018-10-08    285
2018-10-10    335
2018-10-12    218
2018-10-13    434
2018-10-14    368
2018-10-17    216
2018-10-18    200
2018-10-19    158
2018-10-20     67
Name: X, dtype: int64

In [17]:
squirrel_dataset.groupby("Shift").count()['X']

Shift
AM    1347
PM    1676
Name: X, dtype: int64

In [ ]:
# GeoPandas extends Pandas and allows for geographic operations
# We can open shapefiles (yippee!)
# this should be paramount for hw2 me thinks
# loc, finds specific value (.loc['OH'] will find OH)
import geopandas as gpd
import pandas as pd